files:
  - source: /src/Resources/values/strings.xml
    translation: /src/Resources/values-%two_letters_code%/%original_file_name%
  - source: /src/Resources/values/strings.xml
    translation: /src/Resources/values-%android_code%/strings.xml
  - source: /src/Assets/en/*.html
    translation: /src/Assets/%two_letters_code%/%original_file_name%
