// <auto-generated />

namespace ShortDev.Microsoft.ConnectedDevices.Serialization;

public enum PropertyType
{
    PropertyType_Empty = unchecked((int)0),
    PropertyType_Int32 = unchecked((int)4),
    PropertyType_UInt32 = unchecked((int)5),
    PropertyType_UInt64 = unchecked((int)7),
    PropertyType_String = unchecked((int)39),
    PropertyType_GuidArray = unchecked((int)15),
    PropertyType_UInt8Array = unchecked((int)20),
    PropertyType_UInt32Array = unchecked((int)24),
    PropertyType_UInt64Array = unchecked((int)26),
    PropertyType_StringArray = unchecked((int)40),
}

public partial class UUID
{
    public uint Data1 { get; set; }
    public ushort Data2 { get; set; }
    public ushort Data3 { get; set; }
    public ulong Data4 { get; set; }
}

public partial class PropertyValue
{
    public PropertyType Type { get; set; }
    public int Int32Value { get; set; }
    public uint UInt32Value { get; set; }
    public ulong UInt64Value { get; set; }
    public List<UUID> GuidArrayValue { get; set; }
    public string StringValue { get; set; }
    public List<byte> UInt8ArrayValue { get; set; }
    public List<uint> UInt32ArrayValue { get; set; }
    public List<ulong> UInt64ArrayValue { get; set; }
    public List<string> StringArrayValue { get; set; }

    public PropertyValue()
        : this("ShortDev.Microsoft.ConnectedDevices.Serialization.PropertyValue", "PropertyValue")
    { }

    protected PropertyValue(string fullName, string name)
    {
        Type = PropertyType.PropertyType_Empty;
        GuidArrayValue = new List<UUID>();
        StringValue = "";
        UInt8ArrayValue = new List<byte>();
        UInt32ArrayValue = new List<uint>();
        UInt64ArrayValue = new List<ulong>();
        StringArrayValue = new List<string>();
    }
}

public partial class ValueSet
{
    public Dictionary<string, PropertyValue> Entries { get; set; }

    public ValueSet()
        : this("ShortDev.Microsoft.ConnectedDevices.Serialization.ValueSet", "ValueSet")
    { }

    protected ValueSet(string fullName, string name)
    {
        Entries = new Dictionary<string, PropertyValue>();
    }
}
