name: Documentation

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Configure .NET
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.x.x"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Workloads
        run: |
          dotnet workload install android --ignore-failed-sources

      - name: Install docfx
        run: |
          dotnet tool update -g docfx
          echo "~/.dotnet/tools" >> $GITHUB_PATH

      - name: Build docs
        run: docfx docfx.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./_site/"

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
